### ISSUE TITLE
Typo in 09?

### ISSUE THREAD

**Issue by dm17** [containous/blog-posts#1]
What's 'authtraefik'? Wouldn't it just be 'traefik' in this case? Found in:
docker-compose-09.yml

**Comment by ldez** [comment]
Hello,

`authtraefik` is the name of the basic auth middleware

https://github.com/containous/blog-posts/blob/8064d3e400273a4e548fca653ea17db804cd0bf4/2019_09_10-101_docker/docker-compose-09.yml#L28

**Comment by dm17** [comment]
Oh, I thought 'basicauth' was the name of the middleware, and the 'authtraefik' would be (docker) service.
