### ISSUE TITLE
Create acme.json manually?

### ISSUE THREAD

**Issue by dm17** [containous/blog-posts#2]
Should a manual creation of acme.json be added to the article? I get this:
"The ACME resolver \"le\" is skipped from the resolvers list because: unable to get ACME account: permissions 755 for /acme.json are too open, please use 600"

Do I need to add anything inside of acme.json, or just create a blank one with the right permissions?
Thanks!

**Comment by ldez** [comment]
as the file is mounted you have to create it before, leave it empty.

If you have more question, could you go the [community forum](https://community.containo.us)

**Comment by dm17** [comment]
OK, it also seems you'd need to declare post 8080 in docker too for your config to work.
Is there a more complete / official docker-compose example you know of?

**Comment by dm17** [comment]
@ldez Thanks a lot - I wanted to let you know the link on your personal site is broken:
https://saythanks.io/to/ldez
So I sent you a PM on the Traefik forum :)

**Comment by ldez** [comment]
The saythanks.io site stopped working. The site seems to be taken over by another user, but I don't know if I can trust this site now. so I will remove link to this site for now.

**Comment by dm17** [comment]
OK then maybe we can discuss in PM (I sent on Traefik forum) some way to pay you to help me get past this sticking point...
